import argparse
import hashlib
import json
import os
import tempfile
from datetime import datetime, timezone

import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq

from azure.identity import DefaultAzureCredential
from azure.storage.filedatalake import DataLakeServiceClient


STORAGE_ACCOUNT = "sttransactionbello"
FILESYSTEM = "synapse"

BATCH_BRONZE = "bronze/transactions/batch/transactions_batch.csv"
STREAM_BRONZE = "bronze/transactions/streaming"

SILVER_DIR = "silver/transactions"
QUARANTINE_DIR = "quarantine/transactions"
AUDIT_DIR = "audit/dq_metrics"

CHUNK_SIZE = 50_000
STREAMING_BATCH_SIZE = 50_000


def utc_now():
    return datetime.now(timezone.utc).isoformat()


def get_filesystem():
    credential = DefaultAzureCredential(
        exclude_shared_token_cache_credential=True
    )

    service = DataLakeServiceClient(
        account_url=f"https://{STORAGE_ACCOUNT}.dfs.core.windows.net",
        credential=credential,
    )

    return service.get_file_system_client(FILESYSTEM)


def download_file(filesystem, remote_path):
    local_file = tempfile.NamedTemporaryFile(
        delete=False,
        suffix=".data",
    )
    local_file.close()

    client = filesystem.get_file_client(remote_path)

    with open(local_file.name, "wb") as output:
        download = client.download_file()
        download.readinto(output)

    return local_file.name


def upload_bytes(filesystem, remote_path, data):
    client = filesystem.get_file_client(remote_path)
    client.upload_data(data, overwrite=True)


def dataframe_to_parquet_bytes(df):
    table = pa.Table.from_pandas(
        df,
        preserve_index=False,
    )

    buffer = pa.BufferOutputStream()
    pq.write_table(table, buffer)

    return buffer.getvalue().to_pybytes()


def generate_batch_event_ids(df):
    stable_values = (
        df["trans_date_trans_time"].astype(str)
        + "|"
        + df["cc_num"].astype(str)
        + "|"
        + df["amt"].astype(str)
        + "|"
        + df["merchant"].astype(str)
    )

    return [
        hashlib.sha256(
            value.encode("utf-8")
        ).hexdigest()
        for value in stable_values
    ]


def validate_chunk(df, seen_ids):
    df = df.copy()

    if "Unnamed: 0" in df.columns:
        df = df.drop(columns=["Unnamed: 0"])

    # Batch records need a deterministic event ID.
    # Streaming records already contain the event ID
    # generated by the Event Hubs producer.
    if "event_id" not in df.columns:
        df["event_id"] = generate_batch_event_ids(df)

    if "event_time" not in df.columns:
        df["event_time"] = df["trans_date_trans_time"]

    if "ingestion_time" not in df.columns:
        df["ingestion_time"] = utc_now()

    if "source" not in df.columns:
        df["source"] = "sparkov_simulated_transactions"

    numeric_columns = [
        "amt",
        "lat",
        "long",
        "merch_lat",
        "merch_long",
        "city_pop",
        "unix_time",
        "is_fraud",
    ]

    for column in numeric_columns:
        if column in df.columns:
            df[column] = pd.to_numeric(
                df[column],
                errors="coerce",
            )

    reasons = pd.Series(
        "",
        index=df.index,
    )

    def add_reason(mask, reason):
        nonlocal reasons

        reasons.loc[
            mask & (reasons == "")
        ] = reason

    add_reason(
        df["event_id"].isna()
        | df["event_id"].astype(str).eq(""),
        "missing_event_id",
    )

    add_reason(
        df["amt"].isna(),
        "missing_amount",
    )

    add_reason(
        df["amt"] < 0,
        "negative_amount",
    )

    add_reason(
        ~df["lat"].between(-90, 90),
        "invalid_latitude",
    )

    add_reason(
        ~df["long"].between(-180, 180),
        "invalid_longitude",
    )

    add_reason(
        ~df["merch_lat"].between(-90, 90),
        "invalid_merchant_latitude",
    )

    add_reason(
        ~df["merch_long"].between(-180, 180),
        "invalid_merchant_longitude",
    )

    add_reason(
        ~df["is_fraud"].isin([0, 1]),
        "invalid_fraud_flag",
    )

    previously_seen = df["event_id"].isin(seen_ids)

    duplicate_within_batch = df["event_id"].duplicated(
        keep="first"
    )

    duplicate_mask = (
        previously_seen
        | duplicate_within_batch
    )

    add_reason(
        duplicate_mask,
        "duplicate_event_id",
    )

    valid_mask = reasons == ""

    valid = df.loc[valid_mask].copy()
    quarantine = df.loc[~valid_mask].copy()

    if not quarantine.empty:
        quarantine["quarantine_reason"] = reasons.loc[
            ~valid_mask
        ]

        quarantine["quarantine_time"] = utc_now()

    seen_ids.update(
        valid["event_id"].astype(str).tolist()
    )

    return valid, quarantine


def process_batch(filesystem, seen_ids, limit=None):
    print("Processing batch Bronze...")

    local_path = download_file(
        filesystem,
        BATCH_BRONZE,
    )

    valid_total = 0
    quarantine_total = 0
    duplicate_total = 0
    chunks_processed = 0

    try:
        for chunk in pd.read_csv(
            local_path,
            chunksize=CHUNK_SIZE,
        ):
            if limit is not None and chunks_processed >= limit:
                break

            valid, quarantine = validate_chunk(
                chunk,
                seen_ids,
            )

            duplicates = (
                quarantine["quarantine_reason"]
                .eq("duplicate_event_id")
                .sum()
                if not quarantine.empty
                else 0
            )

            valid_total += len(valid)
            quarantine_total += len(quarantine)
            duplicate_total += int(duplicates)

            if not valid.empty:
                path = (
                    f"{SILVER_DIR}/batch/"
                    f"part_{chunks_processed:05d}.parquet"
                )

                upload_bytes(
                    filesystem,
                    path,
                    dataframe_to_parquet_bytes(valid),
                )

            if not quarantine.empty:
                path = (
                    f"{QUARANTINE_DIR}/batch/"
                    f"part_{chunks_processed:05d}.parquet"
                )

                upload_bytes(
                    filesystem,
                    path,
                    dataframe_to_parquet_bytes(
                        quarantine
                    ),
                )

            chunks_processed += 1

            print(
                f"Batch chunk {chunks_processed}: "
                f"valid={len(valid):,}, "
                f"quarantine={len(quarantine):,}"
            )

    finally:
        os.unlink(local_path)

    print(
        f"Batch processing finished: "
        f"chunks={chunks_processed:,}, "
        f"valid={valid_total:,}, "
        f"quarantine={quarantine_total:,}, "
        f"duplicates={duplicate_total:,}"
    )

    return (
        valid_total,
        quarantine_total,
        duplicate_total,
    )


def process_streaming(filesystem, seen_ids):
    print("Processing streaming Bronze...")

    paths = []

    for item in filesystem.get_paths(
        path=STREAM_BRONZE,
        recursive=True,
    ):
        if (
            not item["is_directory"]
            and item["name"].endswith(".jsonl")
        ):
            paths.append(item["name"])

    paths.sort()

    print(
        f"Found {len(paths):,} streaming Bronze files."
    )

    rows_received = 0
    valid_total = 0
    quarantine_total = 0
    duplicate_total = 0

    buffer = []
    output_index = 0

    def flush_buffer():
        nonlocal buffer
        nonlocal output_index
        nonlocal valid_total
        nonlocal quarantine_total
        nonlocal duplicate_total

        if not buffer:
            return

        df = pd.DataFrame(buffer)

        valid, quarantine = validate_chunk(
            df,
            seen_ids,
        )

        duplicates = (
            quarantine["quarantine_reason"]
            .eq("duplicate_event_id")
            .sum()
            if not quarantine.empty
            else 0
        )

        valid_total += len(valid)
        quarantine_total += len(quarantine)
        duplicate_total += int(duplicates)

        if not valid.empty:
            output = (
                f"{SILVER_DIR}/streaming/"
                f"part_{output_index:05d}.parquet"
            )

            upload_bytes(
                filesystem,
                output,
                dataframe_to_parquet_bytes(valid),
            )

        if not quarantine.empty:
            output = (
                f"{QUARANTINE_DIR}/streaming/"
                f"part_{output_index:05d}.parquet"
            )

            upload_bytes(
                filesystem,
                output,
                dataframe_to_parquet_bytes(
                    quarantine
                ),
            )

        print(
            f"Streaming output {output_index}: "
            f"received={len(df):,}, "
            f"valid={len(valid):,}, "
            f"quarantine={len(quarantine):,}, "
            f"duplicates={int(duplicates):,}"
        )

        output_index += 1
        buffer = []

    for index, path in enumerate(paths, start=1):
        client = filesystem.get_file_client(path)

        content = (
            client
            .download_file()
            .readall()
            .decode("utf-8")
        )

        for line in content.splitlines():
            if not line.strip():
                continue

            event = json.loads(line)

            payload = event["payload"].copy()

            payload["event_id"] = event["event_id"]
            payload["event_time"] = event["event_time"]
            payload["ingestion_time"] = event["ingestion_time"]
            payload["source"] = event["source"]

            buffer.append(payload)
            rows_received += 1

            if len(buffer) >= STREAMING_BATCH_SIZE:
                flush_buffer()

        if index % 100 == 0:
            print(
                f"Streaming files "
                f"{index:,}/{len(paths):,} | "
                f"rows received={rows_received:,}"
            )

    flush_buffer()

    print(
        f"Streaming processing finished: "
        f"files={len(paths):,}, "
        f"rows_received={rows_received:,}, "
        f"valid={valid_total:,}, "
        f"quarantine={quarantine_total:,}, "
        f"duplicates={duplicate_total:,}"
    )

    return (
        rows_received,
        valid_total,
        quarantine_total,
        duplicate_total,
    )


def write_metrics(
    filesystem,
    rows_received,
    valid,
    quarantine,
    duplicates,
):
    duplicate_rate = (
        duplicates / rows_received
        if rows_received
        else 0
    )

    dq_pass_rate = (
        valid / rows_received
        if rows_received
        else 0
    )

    metrics = pd.DataFrame(
        [
            {
                "run_time": utc_now(),
                "rows_received": rows_received,
                "rows_valid": valid,
                "rows_quarantined": quarantine,
                "duplicate_rows": duplicates,
                "duplicate_rate": duplicate_rate,
                "dq_pass_rate": dq_pass_rate,
            }
        ]
    )

    path = (
        f"{AUDIT_DIR}/"
        f"run_date="
        f"{datetime.now(timezone.utc).date()}/"
        f"dq_metrics.parquet"
    )

    upload_bytes(
        filesystem,
        path,
        dataframe_to_parquet_bytes(metrics),
    )

    print("\nDQ metrics:")
    print(
        metrics.to_string(index=False)
    )


def main():
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "--batch-chunks",
        type=int,
        default=None,
        help="Process only this many batch chunks.",
    )

    parser.add_argument(
        "--stream-only",
        action="store_true",
        help="Process only streaming Bronze.",
    )

    args = parser.parse_args()

    filesystem = get_filesystem()
    seen_ids = set()

    batch_valid = 0
    batch_quarantine = 0
    batch_duplicates = 0

    if not args.stream_only:
        (
            batch_valid,
            batch_quarantine,
            batch_duplicates,
        ) = process_batch(
            filesystem,
            seen_ids,
            args.batch_chunks,
        )

    (
        stream_received,
        stream_valid,
        stream_quarantine,
        stream_duplicates,
    ) = process_streaming(
        filesystem,
        seen_ids,
    )

    rows_received = (
        batch_valid
        + batch_quarantine
        + stream_received
    )

    valid = (
        batch_valid
        + stream_valid
    )

    quarantine = (
        batch_quarantine
        + stream_quarantine
    )

    duplicates = (
        batch_duplicates
        + stream_duplicates
    )

    write_metrics(
        filesystem,
        rows_received,
        valid,
        quarantine,
        duplicates,
    )

    print(
        "\nDay 6 Bronze → Silver processing complete."
    )


if __name__ == "__main__":
    main()
